import Head from "next/head";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";

const DynamicOrgChart = dynamic(() => import("@/components/OrgChart"), {
  ssr: false, // Disable server-side rendering for this component
});

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Furrl</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <DynamicOrgChart />
      </main>
    </>
  );
}
